image: ubuntu2004

environment:
  matrix:
  - TOXENV: py38
    PYTHON: "3.8"
  - TOXENV: py39
    PYTHON: "3.9"
  - TOXENV: py310
    PYTHON: "3.10"
  - TOXENV: py311
    PYTHON: "3.11"
  - TOXENV: py312
    PYTHON: "3.11"

stack: python $PYTHON

install:
- pip install tox

test_script:
- tox

build: off

skip_commits:
  files:
  - docs/*
  - Readme.rst
  - LICENSE
  - MANIFEST.in
  - .gitignore
