__title__ = "pycrossva"
__description__ = "prepare data from WHO and PHRMC instruments for verbal autopsy algorithms"
__url__ = "https://github.com/verbal-autopsy-software/pyCrossVA"
__version__ = "0.95"
__author__ = "ekarpinskiMITRE, pkmitre, owentrigueros, Peter Choi, & Jason Thomas"
__maintainer__ = "Jason Thomas"
__maintainer_email__ = "jarathomas@gmail.com"
__license__ = "GPLv3"
